name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x]
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    steps:
    - if: runner.os == 'Linux'
      name: Install linux deps
      run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:ci
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/coverage.json
        fail_ci_if_error: true
