name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  testing:
    name: Tests
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
	- run: npm run test:ci
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/coverage.json
        fail_ci_if_error: true
